---
title: État de l'art des unikernels
author: Ludovic Muller
date: Vendredi 10 mai 2019
bibliography: references.bib
reference-section-title: Références
output: pdf_document
biblio-style: plain
papersize: a4paper
lang: fr
numbersections: true
geometry: "margin=3cm"
header-includes:
  - \usepackage[right, modulo]{lineno}
---

